id: IC8409C35
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:46:12+00:00'
last_modified: '2022-06-08T13:19:06.122569+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC319
  title: 'དོན་གྲུབ་རྒྱལ་གྱི་བརྩམས་སྒྲུང་ཕྱོགས་བསྒྲིགས། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4C2F:
      image_group_id: I2PD18187
      title: ''
      total_pages: 420
      order: 1
      base_file: 4C2F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
