id: P010400
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC319
  title: 'དོན་གྲུབ་རྒྱལ་གྱི་བརྩམས་སྒྲུང་ཕྱོགས་བསྒྲིགས། '
  author: ''
  volumes:
    ace06970c3f04101a9ce867e8b512ad6:
      image_group_id: I2PD18187
      title: ''
      volume_number: 1
      total_pages: 420
      base_file: v001.txt
